## PyTorch Basics

In [24]:
import torch
import numpy as np

In [16]:
x = torch.empty(6,3)
print(x)

tensor([[1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39],
        [1.0653e-38, 4.1327e-39, 1.0194e-38]])


In [3]:
y = torch.randn(5,3)
print(y)

tensor([[ 0.6007, -0.1978,  0.2115],
        [-0.8638,  0.0965,  0.9455],
        [ 0.7781,  0.2224,  0.7737],
        [-1.0410,  0.3707,  1.9688],
        [-0.1346,  0.7352,  0.7162]])


In [7]:
z = torch.zeros(5,3,dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
z = torch.tensor([5.5,3])
print(z)

tensor([5.5000, 3.0000])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6007, -0.1978,  0.2115],
        [-0.8638,  0.0965,  0.9455],
        [ 0.7781,  0.2224,  0.7737],
        [-1.0410,  0.3707,  1.9688],
        [-0.1346,  0.7352,  0.7162]])


In [17]:
print(x[:,2]) #NumPy-like indexing

tensor([1.0194e-38, 9.1837e-39, 1.0653e-38, 1.0194e-38, 9.9184e-39, 1.0194e-38])


In [20]:
#Resizing using torch.view()
a = torch.randn(4,4)
b = a.view(16)
c = a.view(-1,8)

In [21]:
print(b)

tensor([-1.3586,  0.9107,  0.5895, -1.7699,  0.5943, -1.7942, -0.4786,  0.2503,
        -0.7705,  1.2964,  0.2701, -2.4702, -0.0813, -1.3886,  0.5643,  0.8193])


In [22]:
print(c)

tensor([[-1.3586,  0.9107,  0.5895, -1.7699,  0.5943, -1.7942, -0.4786,  0.2503],
        [-0.7705,  1.2964,  0.2701, -2.4702, -0.0813, -1.3886,  0.5643,  0.8193]])


In [23]:
#Converting torch tensor to numpy array
d = a.numpy()
print(d)

[[-1.3585852   0.91068137  0.5895272  -1.7698894 ]
 [ 0.59433013 -1.7941643  -0.47863564  0.25029963]
 [-0.7705383   1.2964286   0.27012482 -2.4702299 ]
 [-0.08126742 -1.3886442   0.564267    0.81933576]]


In [26]:
a = np.ones(6)
b = torch.from_numpy(a)
np.add(a, 2, out=a)
print(a)
print(b)

[3. 3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3., 3.], dtype=torch.float64)
